version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: level
      POSTGRES_DB: Level
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: level
      DATABASE_NAME: Level
    ports:
      - "3000:3000"
    depends_on:
      - postgres
