apiVersion: v1
kind: Service
metadata:
  name: levelup-app-service
spec:
  type: NodePort
  selector:
    app: levelup-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
